### ISSUE TITLE
Doesn't work exactly properly

### ISSUE THREAD

**Issue by biinci** [arcticnoah/aseprite-brush-size-hotkey#2]
hello, i had a question. Aseprite brush application not working properly, problem is pen
 The brush gets bigger even if I do it left and right without touching the tablet. Normally, when you touch the pen and turn it left and right, shouldn't it grow? How do I solve this? (My English sucks. Sorry)

**Comment by arcticnoah** [comment]
Hey, sorry for the late reply, this seems to be an issue - with certain pen tablets (see [issue #1](https://github.com/arcticnoah/aseprite-brush-size-hotkey/issues/1)) and as I'm unsure exactly what might causing this, I likely won't be able to fix it. I'll post a release if I figure out how to solve it!

**Comment by biinci** [comment]
Thank you for feedback!
