### ISSUE TITLE
 How can I uninstall the .exe app?

### ISSUE THREAD

**Issue by jorujiare** [arcticnoah/aseprite-brush-size-hotkey#3]
Just to know. How can I uninstall the .exe app? You never know if he will release his own version. And I don't want it to give conflict, I don't see it in the apps installed on my windows. Please and Thanks.

**Comment by arcticnoah** [comment]
Hey, sorry for the late reply. My application never installs itself, so that's why you can't see it as an installed app.

To remove it from your computer, just delete the application exe that you downloaded and you should be done!
