### ISSUE TITLE
Delay when typing

### ISSUE THREAD

**Issue by Intrivus** [arcticnoah/aseprite-brush-size-hotkey#4]
It got a delay when i type d in aseprite like when i rename a layer i wanna type d and e fast but e is first then it will appear d

**Comment by arcticnoah** [comment]
Yea this is definitely a problem that I've kinda never gotten around to fixing, mostly due to my lack of knowledge about the scripting language. That being said, I'll try sorting this out now!

**Comment by arcticnoah** [comment]
Should be fixed now in the latest release ([v1.1.2](https://github.com/arcticnoah/aseprite-brush-size-hotkey/releases/tag/v1.1.2)). Let me know if this doesn't fix it or if you have any other issues!

**Comment by Intrivus** [comment]
> Should be fixed now in the latest release ([v1.1.2](https://github.com/arcticnoah/aseprite-brush-size-hotkey/releases/tag/v1.1.2)). Let me know if this doesn't fix it or if you have any other issues!

Thank you so much
